#version: '3.9'
#
#services:
#  mysql:
#    image: mysql:8
#    container_name: prestashop-db
#    ports:
#      - 3306:3306
#    networks:
#      - prestashop
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_DATABASE: prestashop
#      MYSQL_ROOT_PASSWORD: prestashop


#  prestashop:
#    image: prestashop/prestashop:1.7
#    container_name: prestashop
#    ports:
#      - 8080:80
#    environment:
#      DB_SERVER: mysql
#    networks:
#      - prestashop
#
#networks:
#  prestashop:


version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: store
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: store